### ISSUE TITLE
[BUG] Can't Dismiss the "Your site is vulnerable to attacks" notification

### ISSUE THREAD

**Issue by inspiredearth** [Highfivery/zero-spam-for-wordpress#319]
I reported this on Wordpress.org. To save some time, you can refer to that [here](https://wordpress.org/support/topic/cant-dismiss-the-your-site-is-vulnerable-to-attacks-notification/).

**Describe the bug**
If Enhanced Protection is enabled (without a license key being entered), this notification displays in WP-ADMIN, and it can't be removed (clicking `Dismiss` takes me to the settings page for the plugin).

> Your site is vulnerable to attacks. Please enter a valid Zero Spam license key under Zero Spam Enhanced Protection. Dismiss

If I disable Enhanced Protection, the notification changes to:

> Your site is vulnerable to attacks. For enhanced protection, please enable Zero Spam Enhanced Protection. Dismiss

Clicking `Dismiss` doesn’t dismiss the message, instead it takes me to the config page for the plug-in, and the notification continues to display. No amount of hitting Dismiss actually gets rid of the message.

**To Reproduce**
Described above

**Expected behavior**
The notification should disappear, and not display any more.

**Additional context**

**Comment by EusebiuOprinoiu** [comment]
For me, the notification can be dismissed, but it's displayed again after a plugin update.
Also, the notification is displayed for all users, regardless of their user role, but only administrators can dismiss it. (they are the only ones that can access the settings page)

**Expected behavior**
- The notification should be displayed to administrators only
- Users should be able to dismiss the notification on all pages and not be redirected to the settings page
- After the notification is dismissed, it should not be displayed again when the plugin is updated
