### ISSUE TITLE
[BUG] DavidWalsh blocks all wpforms submissions

### ISSUE THREAD

**Issue by leewillis77** [Highfivery/zero-spam-for-wordpress#355]
Note: This is effectively a re-opening of #347

**Describe the bug**
With David Walsh protection active, and WPForms integration active, all form submissions are blocked with the error:
"Your IP has been flagged as spam/malicious"

It looks like the relevant classes aren't picked up by the David Walsh detection and needed elements aren't injected into the form.

**To Reproduce**
- Activate David Walsh detection
- Activate the WPForms integration
- Try to submit a form
- See error

**Expected behavior**
- Form submission processed correctly.

**Additional context**
Zero Spam : Version 5.4.6
WPForms Lite : Version 1.8.1.2

**Comment by bmarshall511** [comment]
@leewillis77 We've made an attempt to replicate the issue you mentioned in https://github.com/Highfivery/zero-spam-for-wordpress/issues/347#issuecomment-1548498597. In order to fix it, we'll need to replicate the problem on our end. Could you please provide us with additional details about your setup, including the URLs where this issue is occurring? It would also be helpful to know if there are any third-party plugins that might affect the form or the loading of JavaScript.

If you're comfortable with it, you can send us a message with an admin login through this link: [Contact Us](https://www.zerospam.org/contact/). This will allow us to investigate your specific instance and provide a more accurate solution.

**Comment by leewillis77** [comment]
It appears that for the "broken" site, the inline script that should get added by `class-wpforms.php` (line 174) is not added to the page.

**Comment by bmarshall511** [comment]
Not sure. Since we're unable to replicate, there's not much insight we're able to give, but glad you were able to verify it is indeed working on a fresh install. If you're able to provide us more info on how we can replicate or a copy of the site that's not working, we can look into it further. For now, closing this as it's an issue specific to your installation and not Zero Spam itself.

**Comment by leewillis77** [comment]
Hi Ben; 

I don't think this is specific to me, or a single installation (I have three live sites that all suffer the same problem and need the workaround I posted above to allow form submissions). All three of those sites are built in different ways at different times, so it's clearly not a single-site issue.

While I appreciate that it's not as straightforward to reproduce as either of us would like, I think it's clear that there is an issue with some forms, and my diagnostics above show that there is a timing issue relating to the enqueueing of the inline JS that could be addressed even if you don't want to expend the time and effort to investigate the root-cause.
